apiVersion: v1
kind: Pod
metadata:
  name: liveness-probe
spec:
  containers:
  - name: liveness-probe
    image: busybox
    livenessProbe:
      exec:
        command:
        - cat
        - /tmp/healthy
      initialDelaySeconds: 5
      periodSeconds: 5